<img
            src="img/pikachu.jpg"
            ,
            alt="Pikachu"
            ,
            width="200"
            ,
            align="left"
            ,
            class="pikachu"
          />